// export const CREATE = 'CREATE'
// export const UPDATE = 'UPDATE'
// export const DELETE = 'DELETE'
// export const FETCH_ALL = 'FETCH_ALL'
// export const LIKE = 'LIKE'

// External ActionTypes
export const FETCHED_MOVIES = 'FETCHED_MOVIES'
export const FETCHED_SHOWS = 'FETCHED_SHOWS'
export const FETCHED_VIDEO_GAMES = 'FETCHED_VIDEO_GAMES'
export const FETCHED_BOARD_GAMES = 'FETCHED_BOARD_GAMES'
export const FETCHED_BOOKS = 'FETCHED_BOOKS'
export const FETCHED_MEDIA_DETAILS = 'FETCHED_MEDIA_DETAILS'
export const UPDATED_SEARCH_TERM = 'UPDATED_SEARCH_TERM'
export const FETCHED_ALL_MEDIA = 'FETCHED_ALL_MEDIA'

// page ActionTypes
export const ADDED_MEDIA = 'ADDED_MEDIA'
export const SELECTED_MEDIA = 'SELECTED_MEDIA'
export const UPDATED_CONTEXT_MENU_ANCHOR = 'UPDATED_CONTEXT_MENU_ANCHOR'
export const UPDATED_CONTEXT_MENU_VISIBILITY = 'UPDATED_CONTEXT_MENU_VISIBILITY'
export const SET_HOVERED_ELEMENT = 'SET_HOVERED_ELEMENT'